### ISSUE TITLE
use the same context in all client operations

### ISSUE THREAD

**Issue by mzeevi** [omer5yerushalmi/namespaceLabel#2]
The context [carries deadlines, cancellation signals, and other request-scoped values across API boundaries and between processes](https://pkg.go.dev/context). We should use the same control in all things that require it.

https://github.com/omer5yerushalmi/namespaceLabel/blob/92954488ec59a10f061fafc8d2d4d562a638874e/controllers/namespacelabel_controller.go#L232-L235

Instead of using `context.TODO()`, you can pass it as a parameter to the function from the `Reconcile` function.

**Comment by omer5yerushalmi** [comment]
Can you send me a reference for that implementation, because I saw in kubebuilder book that they use context.TODO()
https://book.kubebuilder.io/reference/watching-resources/externally-managed.html
@mzeevi

**Comment by mzeevi** [comment]
You did it here:

https://github.com/omer5yerushalmi/namespaceLabel/blob/92954488ec59a10f061fafc8d2d4d562a638874e/controllers/namespacelabel_controller.go#L93-L100
